# Generated by Django 4.0 on 2021-12-29 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshortener',
            name='count',
        ),
    ]
